steps:
  # Step 1: Build Docker image and push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA', '.']
images:
  - 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA'

# Step 2: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flask-app-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

timeout: '1200s'
